#pragma once

// GENERATED by tools/generate_render_stubs.py - do not edit by hand.
//
// One stub class per interface that RendererModule::SetupEnv installs.
// Every method logs the first time it is reached and returns a
// value-initialized result, so a renderer_vk session reports exactly which
// parts of the engine it fails to serve, in the order the engine asks.

#include "xrEngine/Render.h"
#include "Include/xrRender/DrawUtils.h"
#include "Include/xrRender/UIRender.h"
#include "Include/xrRender/RenderFactory.h"
#include "Include/xrRender/DebugRender.h"

namespace xray::render::vk
{
// Logged once per call site. A Vulkan session otherwise buries the useful
// line under thousands of repeats of whatever the engine calls per frame.
#define XRVK_STUB(what)\
    do {\
        static bool reported = false;\
        if (!reported)\
        {\
            reported = true;\
            Msg("~ [vk stub] %s", what);\
        }\
    } while (false)

// IRender: 75 pure virtual methods, from src/xrEngine/Render.h
class VKRenderStub final : public IRender
{
public:
    GenerationLevel GetGeneration() const override { XRVK_STUB("IRender::GetGeneration"); return {}; }
    BackendAPI GetBackendAPI() const override { XRVK_STUB("IRender::GetBackendAPI"); return {}; }
    bool is_sun_static() override { XRVK_STUB("IRender::is_sun_static"); return {}; }
    u32 get_dx_level() override { XRVK_STUB("IRender::get_dx_level"); return {}; }
    void create() override { XRVK_STUB("IRender::create"); }
    void destroy() override { XRVK_STUB("IRender::destroy"); }
    void reset_begin() override { XRVK_STUB("IRender::reset_begin"); }
    void reset_end() override { XRVK_STUB("IRender::reset_end"); }
    void level_Load(IReader* fs) override { XRVK_STUB("IRender::level_Load"); }
    void level_Unload() override { XRVK_STUB("IRender::level_Unload"); }
    HRESULT shader_compile(pcstr name, IReader* fs, pcstr pFunctionName, pcstr pTarget, u32 Flags, void*& result) override { XRVK_STUB("IRender::shader_compile"); return {}; }
    void DumpStatistics(IGameFont& font, IPerformanceAlert* alert) override { XRVK_STUB("IRender::DumpStatistics"); }
    pcstr getShaderPath() override { XRVK_STUB("IRender::getShaderPath"); return {}; }
    IRenderVisual* getVisual(int id) override { XRVK_STUB("IRender::getVisual"); return {}; }
    xrImTextureData GetImGuiTextureId(pcstr texture_name) override { XRVK_STUB("IRender::GetImGuiTextureId"); return {}; }
    void add_Visual(u32 context_id, IRenderable* root, IRenderVisual* V, Fmatrix& m) override { XRVK_STUB("IRender::add_Visual"); }
    void add_StaticWallmark(const wm_shader& S, const Fvector& P, float s, CDB::TRI* T, Fvector* V) override { XRVK_STUB("IRender::add_StaticWallmark"); }
    void add_StaticWallmark(IWallMarkArray* pArray, const Fvector& P, float s, CDB::TRI* T, Fvector* V) override { XRVK_STUB("IRender::add_StaticWallmark"); }
    void clear_static_wallmarks() override { XRVK_STUB("IRender::clear_static_wallmarks"); }
    void add_SkeletonWallmark(const Fmatrix* xf, IKinematics* obj, IWallMarkArray* pArray, const Fvector& start, const Fvector& dir, float size) override { XRVK_STUB("IRender::add_SkeletonWallmark"); }
    IRender_ObjectSpecific* ros_create(IRenderable* parent) override { XRVK_STUB("IRender::ros_create"); return {}; }
    void ros_destroy(IRender_ObjectSpecific*&) override { XRVK_STUB("IRender::ros_destroy"); }
    IRender_Light* light_create() override { XRVK_STUB("IRender::light_create"); return {}; }
    IRender_Glow* glow_create() override { XRVK_STUB("IRender::glow_create"); return {}; }
    IRenderVisual* model_CreateParticles(pcstr name) override { XRVK_STUB("IRender::model_CreateParticles"); return {}; }
    IRenderVisual* model_Create(pcstr name, IReader* data = 0) override { XRVK_STUB("IRender::model_Create"); return {}; }
    IRenderVisual* model_CreateChild(pcstr name, IReader* data) override { XRVK_STUB("IRender::model_CreateChild"); return {}; }
    IRenderVisual* model_Duplicate(IRenderVisual* V) override { XRVK_STUB("IRender::model_Duplicate"); return {}; }
    void model_Delete(IRenderVisual*& V, bool bDiscard = false) override { XRVK_STUB("IRender::model_Delete"); }
    void model_Logging(bool bEnable) override { XRVK_STUB("IRender::model_Logging"); }
    void models_Prefetch() override { XRVK_STUB("IRender::models_Prefetch"); }
    void models_Clear(bool b_complete) override { XRVK_STUB("IRender::models_Clear"); }
    bool occ_visible(vis_data& V) override { XRVK_STUB("IRender::occ_visible"); return {}; }
    bool occ_visible(Fbox& B) override { XRVK_STUB("IRender::occ_visible"); return {}; }
    bool occ_visible(sPoly& P) override { XRVK_STUB("IRender::occ_visible"); return {}; }
    void Calculate() override { XRVK_STUB("IRender::Calculate"); }
    void Render() override { XRVK_STUB("IRender::Render"); }
    void RenderMenu() override { XRVK_STUB("IRender::RenderMenu"); }
    void BeforeWorldRender() override { XRVK_STUB("IRender::BeforeWorldRender"); }
    void AfterWorldRender() override { XRVK_STUB("IRender::AfterWorldRender"); }
    void Screenshot(ScreenshotMode mode = SM_NORMAL, pcstr name = nullptr) override { XRVK_STUB("IRender::Screenshot"); }
    void SetPostProcessParams(const SPPInfo& ppi) override { XRVK_STUB("IRender::SetPostProcessParams"); }
    void setGamma(float fGamma) override { XRVK_STUB("IRender::setGamma"); }
    void setBrightness(float fGamma) override { XRVK_STUB("IRender::setBrightness"); }
    void setContrast(float fGamma) override { XRVK_STUB("IRender::setContrast"); }
    void updateGamma() override { XRVK_STUB("IRender::updateGamma"); }
    void OnDeviceDestroy(bool bKeepTextures) override { XRVK_STUB("IRender::OnDeviceDestroy"); }
    void Destroy() override { XRVK_STUB("IRender::Destroy"); }
    void Reset(SDL_Window* hWnd, u32& dwWidth, u32& dwHeight, float& fWidth_2, float& fHeight_2) override { XRVK_STUB("IRender::Reset"); }
    void ObtainRequiredWindowFlags(u32& windowFlags) override { XRVK_STUB("IRender::ObtainRequiredWindowFlags"); }
    void SetupStates() override { XRVK_STUB("IRender::SetupStates"); }
    void OnDeviceCreate(pcstr shName) override { XRVK_STUB("IRender::OnDeviceCreate"); }
    void Create(SDL_Window* hWnd, u32& dwWidth, u32& dwHeight, float& fWidth_2, float& fHeight_2) override { XRVK_STUB("IRender::Create"); }
    void overdrawBegin() override { XRVK_STUB("IRender::overdrawBegin"); }
    void overdrawEnd() override { XRVK_STUB("IRender::overdrawEnd"); }
    void DeferredLoad(bool E) override { XRVK_STUB("IRender::DeferredLoad"); }
    void ResourcesDeferredUpload() override { XRVK_STUB("IRender::ResourcesDeferredUpload"); }
    void ResourcesDeferredUnload() override { XRVK_STUB("IRender::ResourcesDeferredUnload"); }
    void ResourcesGetMemoryUsage(u32& m_base, u32& c_base, u32& m_lmaps, u32& c_lmaps) override { XRVK_STUB("IRender::ResourcesGetMemoryUsage"); }
    void ResourcesDestroyNecessaryTextures() override { XRVK_STUB("IRender::ResourcesDestroyNecessaryTextures"); }
    void ResourcesStoreNecessaryTextures() override { XRVK_STUB("IRender::ResourcesStoreNecessaryTextures"); }
    void ResourcesDumpMemoryUsage() override { XRVK_STUB("IRender::ResourcesDumpMemoryUsage"); }
    bool HWSupportsShaderYUV2RGB() override { XRVK_STUB("IRender::HWSupportsShaderYUV2RGB"); return {}; }
    DeviceState GetDeviceState() override { XRVK_STUB("IRender::GetDeviceState"); return {}; }
    bool GetForceGPU_REF() override { XRVK_STUB("IRender::GetForceGPU_REF"); return {}; }
    u32 GetCacheStatPolys() override { XRVK_STUB("IRender::GetCacheStatPolys"); return {}; }
    void OnCameraUpdated() override { XRVK_STUB("IRender::OnCameraUpdated"); }
    void Begin() override { XRVK_STUB("IRender::Begin"); }
    void Clear() override { XRVK_STUB("IRender::Clear"); }
    void End() override { XRVK_STUB("IRender::End"); }
    void ClearTarget() override { XRVK_STUB("IRender::ClearTarget"); }
    void SetCacheXform(Fmatrix& mView, Fmatrix& mProject) override { XRVK_STUB("IRender::SetCacheXform"); }
    void OnAssetsChanged() override { XRVK_STUB("IRender::OnAssetsChanged"); }
    RenderContext GetCurrentContext() const override { XRVK_STUB("IRender::GetCurrentContext"); return {}; }
    void MakeContextCurrent(RenderContext context) override { XRVK_STUB("IRender::MakeContextCurrent"); }
};

// CDUInterface: 46 pure virtual methods, from src/Include/xrRender/DrawUtils.h
class VKCDUInterfaceStub final : public CDUInterface
{
public:
    void DrawCross(const Fvector& p, float szx1, float szy1, float szz1, float szx2, float szy2, float szz2, u32 clr, BOOL bRot45 = false) override { XRVK_STUB("CDUInterface::DrawCross"); }
    void DrawCross(const Fvector& p, float sz, u32 clr, BOOL bRot45 = false) override { XRVK_STUB("CDUInterface::DrawCross"); }
    void DrawFlag(const Fvector& p, float heading, float height, float sz, float sz_fl, u32 clr, BOOL bDrawEntity) override { XRVK_STUB("CDUInterface::DrawFlag"); }
    void DrawRomboid(const Fvector& p, float radius, u32 clr) override { XRVK_STUB("CDUInterface::DrawRomboid"); }
    void DrawJoint(const Fvector& p, float radius, u32 clr) override { XRVK_STUB("CDUInterface::DrawJoint"); }
    void DrawSpotLight(const Fvector& p, const Fvector& d, float range, float phi, u32 clr) override { XRVK_STUB("CDUInterface::DrawSpotLight"); }
    void DrawDirectionalLight(const Fvector& p, const Fvector& d, float radius, float range, u32 clr) override { XRVK_STUB("CDUInterface::DrawDirectionalLight"); }
    void DrawPointLight(const Fvector& p, float radius, u32 clr) override { XRVK_STUB("CDUInterface::DrawPointLight"); }
    void DrawSound(const Fvector& p, float radius, u32 clr) override { XRVK_STUB("CDUInterface::DrawSound"); }
    void DrawLineSphere(const Fvector& p, float radius, u32 clr, BOOL bCross) override { XRVK_STUB("CDUInterface::DrawLineSphere"); }
    void dbgDrawPlacement(const Fvector& p, int sz, u32 clr, LPCSTR caption = 0, u32 clr_font = 0xffffffff) override { XRVK_STUB("CDUInterface::dbgDrawPlacement"); }
    void dbgDrawVert(const Fvector& p0, u32 clr, LPCSTR caption = 0) override { XRVK_STUB("CDUInterface::dbgDrawVert"); }
    void dbgDrawEdge(const Fvector& p0, const Fvector& p1, u32 clr, LPCSTR caption = 0) override { XRVK_STUB("CDUInterface::dbgDrawEdge"); }
    void dbgDrawFace(const Fvector& p0, const Fvector& p1, const Fvector& p2, u32 clr, LPCSTR caption = 0) override { XRVK_STUB("CDUInterface::dbgDrawFace"); }
    void DrawFace(const Fvector& p0, const Fvector& p1, const Fvector& p2, u32 clr_s, u32 clr_w, BOOL bSolid, BOOL bWire) override { XRVK_STUB("CDUInterface::DrawFace"); }
    void DrawLine(const Fvector& p0, const Fvector& p1, u32 clr) override { XRVK_STUB("CDUInterface::DrawLine"); }
    void DrawLink(const Fvector& p0, const Fvector& p1, float sz, u32 clr) override { XRVK_STUB("CDUInterface::DrawLink"); }
    void DrawFaceNormal(const Fvector& p0, const Fvector& p1, const Fvector& p2, float size, u32 clr) override { XRVK_STUB("CDUInterface::DrawFaceNormal"); }
    void DrawFaceNormal(const Fvector* p, float size, u32 clr) override { XRVK_STUB("CDUInterface::DrawFaceNormal"); }
    void DrawFaceNormal(const Fvector& C, const Fvector& N, float size, u32 clr) override { XRVK_STUB("CDUInterface::DrawFaceNormal"); }
    void DrawSelectionBox(const Fvector& center, const Fvector& size, u32* c = 0) override { XRVK_STUB("CDUInterface::DrawSelectionBox"); }
    void DrawSelectionBoxB(const Fbox& box, u32* c = 0) override { XRVK_STUB("CDUInterface::DrawSelectionBoxB"); }
    void DrawIdentSphere(BOOL bSolid, BOOL bWire, u32 clr_s, u32 clr_w) override { XRVK_STUB("CDUInterface::DrawIdentSphere"); }
    void DrawIdentSpherePart(BOOL bSolid, BOOL bWire, u32 clr_s, u32 clr_w) override { XRVK_STUB("CDUInterface::DrawIdentSpherePart"); }
    void DrawIdentCone(BOOL bSolid, BOOL bWire, u32 clr_s, u32 clr_w) override { XRVK_STUB("CDUInterface::DrawIdentCone"); }
    void DrawIdentCylinder(BOOL bSolid, BOOL bWire, u32 clr_s, u32 clr_w) override { XRVK_STUB("CDUInterface::DrawIdentCylinder"); }
    void DrawIdentBox(BOOL bSolid, BOOL bWire, u32 clr_s, u32 clr_w) override { XRVK_STUB("CDUInterface::DrawIdentBox"); }
    void DrawBox(const Fvector& offs, const Fvector& Size, BOOL bSolid, BOOL bWire, u32 clr_s, u32 clr_w) override { XRVK_STUB("CDUInterface::DrawBox"); }
    void DrawAABB(const Fvector& p0, const Fvector& p1, u32 clr_s, u32 clr_w, BOOL bSolid, BOOL bWire) override { XRVK_STUB("CDUInterface::DrawAABB"); }
    void DrawAABB(const Fmatrix& parent, const Fvector& center, const Fvector& size, u32 clr_s, u32 clr_w, BOOL bSolid, BOOL bWire) override { XRVK_STUB("CDUInterface::DrawAABB"); }
    void DrawOBB(const Fmatrix& parent, const Fobb& box, u32 clr_s, u32 clr_w) override { XRVK_STUB("CDUInterface::DrawOBB"); }
    void DrawSphere(const Fmatrix& parent, const Fvector& center, float radius, u32 clr_s, u32 clr_w, BOOL bSolid, BOOL bWire) override { XRVK_STUB("CDUInterface::DrawSphere"); }
    void DrawSphere(const Fmatrix& parent, const Fsphere& S, u32 clr_s, u32 clr_w, BOOL bSolid, BOOL bWire) override { XRVK_STUB("CDUInterface::DrawSphere"); }
    void DrawCylinder(const Fmatrix& parent, const Fvector& center, const Fvector& dir, float height, float radius, u32 clr_s, u32 clr_w, BOOL bSolid, BOOL bWire) override { XRVK_STUB("CDUInterface::DrawCylinder"); }
    void DrawCone(const Fmatrix& parent, const Fvector& apex, const Fvector& dir, float height, float radius, u32 clr_s, u32 clr_w, BOOL bSolid, BOOL bWire) override { XRVK_STUB("CDUInterface::DrawCone"); }
    void DrawPlane(const Fvector& center, const Fvector2& scale, const Fvector& rotate, u32 clr_s, u32 clr_w, BOOL bCull, BOOL bSolid, BOOL bWire) override { XRVK_STUB("CDUInterface::DrawPlane"); }
    void DrawPlane(const Fvector& p, const Fvector& n, const Fvector2& scale, u32 clr_s, u32 clr_w, BOOL bCull, BOOL bSolid, BOOL bWire) override { XRVK_STUB("CDUInterface::DrawPlane"); }
    void DrawRectangle(const Fvector& o, const Fvector& u, const Fvector& v, u32 clr_s, u32 clr_w, BOOL bSolid, BOOL bWire) override { XRVK_STUB("CDUInterface::DrawRectangle"); }
    void DrawGrid() override { XRVK_STUB("CDUInterface::DrawGrid"); }
    void DrawPivot(const Fvector& pos, float sz = 5.f) override { XRVK_STUB("CDUInterface::DrawPivot"); }
    void DrawAxis(const Fmatrix& T) override { XRVK_STUB("CDUInterface::DrawAxis"); }
    void DrawObjectAxis(const Fmatrix& T, float sz, BOOL sel) override { XRVK_STUB("CDUInterface::DrawObjectAxis"); }
    void DrawSelectionRect(const Ivector2& m_SelStart, const Ivector2& m_SelEnd) override { XRVK_STUB("CDUInterface::DrawSelectionRect"); }
    void DrawIndexedPrimitive(int prim_type, u32 pc, const Fvector& pos, const Fvector* vb, const u32& vb_size, const u32* ib, const u32& ib_size, const u32& clr_argb, float scale = 1.0f) override { XRVK_STUB("CDUInterface::DrawIndexedPrimitive"); }
    void OutText(const Fvector& pos, LPCSTR text, u32 color = 0xFF000000, u32 shadow_color = 0xFF909090) override { XRVK_STUB("CDUInterface::OutText"); }
    void OnDeviceDestroy() override { XRVK_STUB("CDUInterface::OnDeviceDestroy"); }
};

// IUIRender: 11 pure virtual methods, from src/Include/xrRender/UIRender.h
class VKUIRenderStub final : public IUIRender
{
public:
    void CreateUIGeom() override { XRVK_STUB("IUIRender::CreateUIGeom"); }
    void DestroyUIGeom() override { XRVK_STUB("IUIRender::DestroyUIGeom"); }
    void SetShader(IUIShader& shader) override { XRVK_STUB("IUIRender::SetShader"); }
    void SetAlphaRef(int aref) override { XRVK_STUB("IUIRender::SetAlphaRef"); }
    void SetScissor(Irect* rect = nullptr) override { XRVK_STUB("IUIRender::SetScissor"); }
    void PushPoint(float x, float y, float z, u32 C, float u, float v) override { XRVK_STUB("IUIRender::PushPoint"); }
    void StartPrimitive(u32 iMaxVerts, ePrimitiveType primType, ePointType pointType) override { XRVK_STUB("IUIRender::StartPrimitive"); }
    void FlushPrimitive() override { XRVK_STUB("IUIRender::FlushPrimitive"); }
    LPCSTR UpdateShaderName(LPCSTR tex_name, LPCSTR sh_name) override { XRVK_STUB("IUIRender::UpdateShaderName"); return {}; }
    void CacheSetXformWorld(const Fmatrix& M) override { XRVK_STUB("IUIRender::CacheSetXformWorld"); }
    void CacheSetCullMode(CullMode) override { XRVK_STUB("IUIRender::CacheSetCullMode"); }
};

// IRenderFactory: 28 pure virtual methods, from src/Include/xrRender/RenderFactory.h
class VKRenderFactoryStub final : public IRenderFactory
{
public:
#ifndef _EDITOR
    IUISequenceVideoItem* CreateUISequenceVideoItem() override { XRVK_STUB("IRenderFactory::CreateUISequenceVideoItem"); return {}; }
    void DestroyUISequenceVideoItem(IUISequenceVideoItem* pObject) override { XRVK_STUB("IRenderFactory::DestroyUISequenceVideoItem"); }
    IUIShader* CreateUIShader() override { XRVK_STUB("IRenderFactory::CreateUIShader"); return {}; }
    void DestroyUIShader(IUIShader* pObject) override { XRVK_STUB("IRenderFactory::DestroyUIShader"); }
    IStatGraphRender* CreateStatGraphRender() override { XRVK_STUB("IRenderFactory::CreateStatGraphRender"); return {}; }
    void DestroyStatGraphRender(IStatGraphRender* pObject) override { XRVK_STUB("IRenderFactory::DestroyStatGraphRender"); }
#ifdef DEBUG
    IObjectSpaceRender* CreateObjectSpaceRender() override { XRVK_STUB("IRenderFactory::CreateObjectSpaceRender"); return {}; }
    void DestroyObjectSpaceRender(IObjectSpaceRender* pObject) override { XRVK_STUB("IRenderFactory::DestroyObjectSpaceRender"); }
#endif
    IWallMarkArray* CreateWallMarkArray() override { XRVK_STUB("IRenderFactory::CreateWallMarkArray"); return {}; }
    void DestroyWallMarkArray(IWallMarkArray* pObject) override { XRVK_STUB("IRenderFactory::DestroyWallMarkArray"); }
    IEnvironmentRender* CreateEnvironmentRender() override { XRVK_STUB("IRenderFactory::CreateEnvironmentRender"); return {}; }
    void DestroyEnvironmentRender(IEnvironmentRender* pObject) override { XRVK_STUB("IRenderFactory::DestroyEnvironmentRender"); }
    IEnvDescriptorRender* CreateEnvDescriptorRender() override { XRVK_STUB("IRenderFactory::CreateEnvDescriptorRender"); return {}; }
    void DestroyEnvDescriptorRender(IEnvDescriptorRender* pObject) override { XRVK_STUB("IRenderFactory::DestroyEnvDescriptorRender"); }
    IRainRender* CreateRainRender() override { XRVK_STUB("IRenderFactory::CreateRainRender"); return {}; }
    void DestroyRainRender(IRainRender* pObject) override { XRVK_STUB("IRenderFactory::DestroyRainRender"); }
    ILensFlareRender* CreateLensFlareRender() override { XRVK_STUB("IRenderFactory::CreateLensFlareRender"); return {}; }
    void DestroyLensFlareRender(ILensFlareRender* pObject) override { XRVK_STUB("IRenderFactory::DestroyLensFlareRender"); }
    IImGuiRender* CreateImGuiRender() override { XRVK_STUB("IRenderFactory::CreateImGuiRender"); return {}; }
    void DestroyImGuiRender(IImGuiRender* pObject) override { XRVK_STUB("IRenderFactory::DestroyImGuiRender"); }
    IThunderboltRender* CreateThunderboltRender() override { XRVK_STUB("IRenderFactory::CreateThunderboltRender"); return {}; }
    void DestroyThunderboltRender(IThunderboltRender* pObject) override { XRVK_STUB("IRenderFactory::DestroyThunderboltRender"); }
    IThunderboltDescRender* CreateThunderboltDescRender() override { XRVK_STUB("IRenderFactory::CreateThunderboltDescRender"); return {}; }
    void DestroyThunderboltDescRender(IThunderboltDescRender* pObject) override { XRVK_STUB("IRenderFactory::DestroyThunderboltDescRender"); }
    IFlareRender* CreateFlareRender() override { XRVK_STUB("IRenderFactory::CreateFlareRender"); return {}; }
    void DestroyFlareRender(IFlareRender* pObject) override { XRVK_STUB("IRenderFactory::DestroyFlareRender"); }
#endif
    IFontRender* CreateFontRender() override { XRVK_STUB("IRenderFactory::CreateFontRender"); return {}; }
    void DestroyFontRender(IFontRender* pObject) override { XRVK_STUB("IRenderFactory::DestroyFontRender"); }
};

// IDebugRender: 12 pure virtual methods, from src/Include/xrRender/DebugRender.h
class VKDebugRenderStub final : public IDebugRender
{
public:
    void Render() override { XRVK_STUB("IDebugRender::Render"); }
    void add_lines(Fvector const* vertices, u32 const& vertex_count, u16 const* pairs, u32 const& pair_count, u32 const& color) override { XRVK_STUB("IDebugRender::add_lines"); }
    void NextSceneMode() override { XRVK_STUB("IDebugRender::NextSceneMode"); }
    void ZEnable(bool bEnable) override { XRVK_STUB("IDebugRender::ZEnable"); }
    void OnFrameEnd() override { XRVK_STUB("IDebugRender::OnFrameEnd"); }
    void SetShader(const debug_shader& shader) override { XRVK_STUB("IDebugRender::SetShader"); }
    void CacheSetXformWorld(const Fmatrix& M) override { XRVK_STUB("IDebugRender::CacheSetXformWorld"); }
    void CacheSetCullMode(CullMode) override { XRVK_STUB("IDebugRender::CacheSetCullMode"); }
    void SetAmbient(u32 colour) override { XRVK_STUB("IDebugRender::SetAmbient"); }
    void SetDebugShader(dbgShaderHandle shdHandle) override { XRVK_STUB("IDebugRender::SetDebugShader"); }
    void DestroyDebugShader(dbgShaderHandle shdHandle) override { XRVK_STUB("IDebugRender::DestroyDebugShader"); }
#ifdef DEBUG
    void dbg_DrawTRI(Fmatrix& T, Fvector& p1, Fvector& p2, Fvector& p3, u32 C) override { XRVK_STUB("IDebugRender::dbg_DrawTRI"); }
#endif
};

#undef XRVK_STUB
} // namespace xray::render::vk
